package com.example.financetrackerapplication.model

data class UserModel(
    var userId: String = "", // Unique user ID (generated by Firebase)
    var email: String = "", // User's email
    var username: String = "", // User's username (extracted from the email)
    var password: String = "" // User's password
)
